// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wtcrvlwrqakaklsexchk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind0Y3J2bHdycWFrYWtsc2V4Y2hrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1MjMxNTMsImV4cCI6MjA2NzA5OTE1M30.v1AMwPNPQNIC1TcjxVegDeq-VW9uDt4ukQyOpPfUWow";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});